In [14]:
import pytesseract
from pytesseract import Output
import cv2
import os

In [15]:
pytesseract.pytesseract.tesseract_cmd = r'D:\Program Files\Tesseract-OCR\tesseract.exe'

In [16]:
def flatten(t):
    return [item for list in t for item in list]

# Task 1 method

In [4]:
def task1out(fname, result):
    formatted_output = []
    for line in result:
        formatted_output.append([int(n) for n in line[:8]])

    with open(fname, 'w') as f:
        for row in formatted_output:
            f.write(','.join(str(v).upper() for v in row) + '\n')

# Task 2 method

In [5]:
def task2out(fname, result):
    formatted_output = []

    for line in result:
        out = [str(line[8]).upper()]
        formatted_output.append(out)

    with open(fname, 'w') as f:
        for row in formatted_output:
            for token in row:
                f.write(token+'\n')

# Get results

In [24]:
img_dir = 'Datasets/SROIE2019/preprocessed'
result_dir = 'Datasets/SROIE2019/tesseract'
images = [os.path.splitext(filename)[0] for filename in os.listdir(img_dir)]

In [25]:
for idx, image in enumerate(images):
    if idx % 50 == 0:
        print(idx+1,'/',len(images))
    img_path = os.path.join(img_dir, image + '.jpg')
    result1_path = os.path.join(result_dir, 'task 1', image + '.txt')
    result2_path = os.path.join(result_dir, 'task 2', image + '.txt')
    
    img = cv2.imread(img_path)
    h, w, _ = img.shape

    d = pytesseract.image_to_data(img, output_type=Output.DATAFRAME)
    boxes = []

    d = d[d.conf != -1]

    for i, row in d.iterrows():
        x1 = row['left']
        y1 = row['top']
        x2 = row['left']+row['width']
        y2 = y1
        x3 = x2
        y3 = row['top']+row['height']
        x4 = x1
        y4 = y3

        boxes.append([x1,y1,x2,y2,x3,y3,x4,y4,row['text']])

    task1out(result1_path, boxes)
    task2out(result2_path, boxes)

1 / 986
51 / 986
101 / 986
151 / 986
201 / 986
251 / 986
301 / 986
351 / 986
401 / 986
451 / 986
501 / 986
551 / 986
601 / 986
651 / 986
701 / 986
751 / 986
801 / 986
851 / 986
901 / 986
951 / 986

In [23]:
image = 'X00016469619'
img_path = os.path.join(img_dir, image + '.jpg')
result1_path = os.path.join(result_dir, 'task 1', image + '.txt')
result2_path = os.path.join(result_dir, 'task 2', image + '.txt')

img = cv2.imread(img_path)
h, w, _ = img.shape

data = pytesseract.image_to_data(img, output_type=Output.DATAFRAME)

print(data)

d = pytesseract.image_to_data(img, output_type=Output.DATAFRAME)
boxes = []

d = d[d.conf != -1]
d = d[d.text != ' ']

for i, row in d.iterrows():
    x1 = row['left']
    y1 = row['top']
    x2 = row['left']+row['width']
    y2 = y1
    x3 = x2
    y3 = row['top']+row['height']
    x4 = x1
    y4 = y3

    boxes.append([x1,y1,x2,y2,x3,y3,x4,y4,row['text']])
    (x, y, w, h) = (row['left'], row['top'], row['width'], row['height'])
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)

print(boxes[0])
cv2.imshow('img', img)
cv2.waitKey(0)                              # return last line

#task1out(result1_path, result)
#task2out(result2_path, result)

     level  page_num  block_num  par_num  line_num  word_num  left  top  \
0        1         1          0        0         0         0     0    0
1        2         1          1        0         0         0    78   52
2        3         1          1        1         0         0    78   52
3        4         1          1        1         1         0    78   52
4        5         1          1        1         1         1    78   52
..     ...       ...        ...      ...       ...       ...   ...  ...
134      5         1         11        1         3         5   300  942
135      2         1         12        0         0         0   291  917
136      3         1         12        1         0         0   291  917
137      4         1         12        1         1         0   291  917
138      5         1         12        1         1         1   291  917

     width  height       conf text
0      439    1004  -1.000000  NaN
1      244      31  -1.000000  NaN
2      244      31  -1.000000  NaN
3      244      31  -1.000000  NaN
4       52      23  93.060196  tan
..     ...     ...        ...  ...
134      7      13  29.558960    f
135     67      43  -1.000000  NaN
136     67      43  -1.000000  NaN
137     67      43  -1.000000  NaN
138     67      43  95.000000

[139 rows x 12 columns]
[78, 52, 130, 52, 130, 75, 78, 75, 'tan']

-1

In [21]:
d[60:]

,level,page_num,block_num,par_num,line_num,word_num,left,top,width,height,conf,text
99,5,1,8,1,3,1,28,696,44,14,92.896996,TOTAL
100,5,1,8,1,3,2,84,695,35,15,83.522552,AHT.
102,5,1,8,1,4,1,29,720,73,15,93.654114,ROUNDING
103,5,1,8,1,4,2,113,720,33,15,71.964920,ADI.
107,5,1,9,1,1,1,121,690,162,24,95.000000,
111,5,1,10,1,1,1,24,726,260,112,95.000000,
112,5,1,10,1,1,2,296,640,112,196,95.000000,
116,5,1,11,1,1,1,66,894,45,14,96.826706,Thank
117,5,1,11,1,1,2,122,893,26,15,92.965958,You
118,5,1,11,1,1,3,163,894,2,14,81.696777,!
119,5,1,11,1,1,4,178,893,55,15,96.365486,Please
120,5,1,11,1,1,5,244,892,36,15,96.899345,Come
121,5,1,11,1,1,6,291,893,45,18,45.263870,Again
122,5,1,11,1,1,7,350,893,2,14,92.503540,!
124,5,1,11,1,2,1,75,919,45,14,86.555168,Goods
125,5,1,11,1,2,2,131,918,36,15,96.836334,Sold
126,5,1,11,1,2,3,178,918,26,14,93.185799,Are
127,5,1,11,1,2,4,216,918,26,14,93.273384,Not
128,5,1,11,1,2,5,253,917,36,15,79.575630,Retui
130,5,1,11,1,3,1,67,943,63,19,44.365120,Healing
131,5,1,11,1,3,2,142,943,16,14,95.330765,In
132,5,1,11,1,3,3,169,942,83,15,91.273285,Wholesale
133,5,1,11,1,3,4,263,943,26,14,89.947159,And
134,5,1,11,1,3,5,300,942,7,13,29.558960,f
138,5,1,12,1,1,1,291,917,67,43,95.000000,